# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra', '2.1.0'
# gem "rails"
gem 'sinatra-contrib', '2.1.0'
gem 'rspec' , '~>3.0'   
gem 'rack-cors'
gem 'openssl', '~> 3.1'
gem 'pg', '~> 1.5', '>= 1.5.9'
gem 'bcrypt'
gem 'webrick'
gem 'base64', '~> 0.1.0'